name: Speak Up Sing Out
favicon: null
layout_spectrum: 0.6600138591602445
typography_spectrum: 0.32752
title: Speak Up Sing Out
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4375
  lightness: 0.45899535925127566
  saturation: 0.6028545836452395
  rhythmicContrast: 0.4078850999940187
purpose: []
