name: Speak Up Sing Out
favicon: null
layout_spectrum: 0.5625
typography_spectrum: 0.32752
title: Speak Up Sing Out
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#d22828'
    - '#f5c4c3'
    - '#767676'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
