name: Speak Up Sing Out
favicon: null
layout_spectrum: 0.25423
typography_spectrum: 0.32752
title: Speak Up Sing Out
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090f0f'
    - '#e7f5f8'
    - '#80cfd4'
    - '#567160'
    - '#d1242a'
  brandStrength: 0.4375
  lightness: 0.45899535925127566
  saturation: 0.6028545836452395
  rhythmicContrast: 0.4078850999940187
purpose: []
